name: Update HTML From SharePoint

on:
  schedule:
    - cron: "*/5 * * * *"    # kör var 5:e minut
  workflow_dispatch:          # gör att du kan köra manuellt

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download HTML from SharePoint
        run: |
          curl -L "https://svedalaonline.sharepoint.com/sites/team-svedala-tn-utbildning-Barafrmig/Delade%20dokument/AllergenerAuto/Temp/Allergener.html" -o index.html

      - name: Commit and push if changed
        run: |
          git config user.name "auto-updater"
          git config user.email "no-reply@svedala.se"
          git add index.html
          git commit -m "Auto update from SharePoint" || echo "No changes"
          git push
``
