name: Update index.html from source

on:
  schedule:
    - cron: "*/5 * * * *"     # var 5:e minut (UTC)
  workflow_dispatch: {}        # k√∂r manuellt

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Fetch latest index.html
        run: |
          curl -L "https://www.dropbox.com/scl/fi/rmhgugdeondsxwh4i6xcq/Allergener.html?rlkey=3xszzhuplvikbcyjvhrjuepj0&st=8piezvnd&dl=1" -o index.html

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "github-actions@github.com"
            git config --global user.name  "GitHub Actions"
            git add index.html
            git commit -m "Auto-update index.html"
            git push
          else
            echo "No changes"
          fi
