name: Update HTML From Dropbox

on:
  schedule:
    - cron: "*/5 * * * *"  # k√∂r var 5:e minut
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download HTML
        run: |
          curl -L "https://dl.dropboxusercontent.com/scl/fi/rmhgugdeondsxwh4i6xcq/Allergener.html?rlkey=3xszzhuplvikbcyjvhrjuepj0&st=o75tf5bn" -o index.html
          head -n 5 index.html

      - name: Commit and push if changed
        run: |
          git config user.name "auto-updater"
          git config user.email "no-reply@svedala.se"
          git add index.html
          git commit -m "Auto update from Dropbox" || echo "No changes"
          git push
